name: Create release tag of git

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: タグ名。"r"(本番)または"d"(プレビュー環境)から始まる値を入力。e.g. "d0.1.0"
        required: true
      tag_headline:
        description: タグのタイトル。基本的にリリースPRのタイトルを入力。
        required: true
      tag_description:
        description: タグの詳細。基本的にリリースPRのURLを入力。
        required: true
      release_date:
        description: リリース日時。"YYYYMMDDHH"を入力。即時リリースの場合は省略。e.g. "2021090113" (2021/09/01 13:00にリリース)
        required: false

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
      # 入力値の出力
      - name: Output variables
        run: |
          echo "tag_name: ${{ github.event.inputs.tag_name }}"
          echo "tag_headline: ${{ github.event.inputs.tag_headline }}"
          echo "tag_description: ${{ github.event.inputs.tag_description }}"
          echo "release_date: ${{ github.event.inputs.release_date }}"

      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # バリデーション - タグ名のチェック
      - name: Validate tag_name
        run: |
          if [[ !(${{ github.event.inputs.tag_name }} =~ "^[r|d][0-9]+.[0-9]+.[0-9]+$") ]]; then
            echo "タグ名がフォーマット違反です。タグ名: ${{ github.event.inputs.tag_name }}"
            exit 1
          fi

      # バリデーション - デプロイ日時が現時刻〜1週間後に収まっていることのチェック
      - name: Validate release_date
        run: |
          if [ -z ${{ github.event.inputs.release_date }} ]; then
            exit 0
          fi

          CURRENT_DATETIME=`TZ='Asia/Tokyo' date '+%Y%m%d%H'`
          AFTER_WEEK_DATETIME=`TZ='Asia/Tokyo' date '+%Y%m%d%H' -d '7 days'`

          if ((${{ github.event.inputs.release_date }} <= ${CURRENT_DATETIME} || ${{ github.event.inputs.release_date }} > ${AFTER_WEEK_DATETIME})); then
            echo "デプロイ日時には現在〜1週間後を設定してください。デプロイ日時: ${{ github.event.inputs.release_date }}"
            exit 1
          fi

      # タグの作成とpush
      - name: Create tag and push
        run: |
          git config user.email "tag_creator@example.com"
          git config user.name "tag creator"

          git tag -a ${{ github.event.inputs.tag_name }} -F- <<EOM
          ${{ github.event.inputs.tag_headline }}

          ${{ github.event.inputs.tag_description }}
          EOM
          git push origin ${{ github.event.inputs.tag_name }}
