name: Create release tag of git

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: タグ名。"r"(本番)または"d"(プレビュー環境)から始まる値を入力。e.g. "d0.1.0"
        required: true
      tag_headline:
        description: タグのタイトル。基本的にリリースPRのタイトルを入力。
        required: true
      tag_description:
        description: タグの詳細。基本的にリリースPRのURLを入力。
        required: true
      release_date:
        description: リリース日時。"YYYYMMDDHH"を入力。即時リリースの場合は省略。e.g. "2021090113" (2021/09/01 13:00にリリース)
        required: false

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
      # 入力値の出力
      - name: Output variables
        run: |
          echo "tag_name: ${{ github.event.inputs.tag_name }}"
          echo "tag_headline: ${{ github.event.inputs.tag_headline }}"
          echo "tag_description: ${{ github.event.inputs.tag_description }}"
          echo "release_date: ${{ github.event.inputs.release_date }}"

      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # バリデーション
      - name: Validate
        run: |
          echo 'todo validation'

      # タグの作成とpush
      - name: Create tag and push
        run: |
          git config user.email "tag_creator@example.com"
          git config user.name "tag creator"

          git tag -a ${{ github.event.inputs.tag_name }} -m "${{ github.event.inputs.tag_body }}\n\n${{ github.event.inputs.tag_body }}"
          git push origin ${{ github.event.inputs.tag_name }}
