name: fuga
on:
  push:
    tags:
      - r[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # デプロイ日時の取得とワークフロー内変数の定義
      - name: Define variable of deploy date
        id: deploy_date_variable
        run: |
          TAG_NAME=`echo ${{ github.ref }} | sed -e "s#refs/tags/##g"`
          echo "aaaaa"
          echo ${TAG_NAME}
          git tag -n
          git tag --list ${TAG_NAME} -n
          git tag -v ${TAG_NAME}
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l --format='%(contents:subject)' ${TAG_NAME}
          # TAG_MESSAGE=`git tag -n | grep ${TAG_NAME}`
          DEPLOY_DATETIME=`echo ${TAG_MESSAGE} | sed -r 's/^.*\(([0-9]{3})\)$/\1/'`

          CURRENT_DATETIME=`date '+%Y%m%d%H'`
          AFTER_WEEK_DATETIME=`date '+%Y%m%d%H' -d '7 days'`

          if(($CURRENT_DATETIME < $DEPLOY_DATETIME && $DEPLOY_DATETIME <= $AFTER_WEEK_DATETIME)); then
            echo "::set-output name=suffix::.${$DEPLOY_DATETIME}"
          else
            echo "::set-output name=suffix::.${$DEPLOY_DATETIME}"
          fi

      - name: hoge
        run: |
          echo ${{ steps.deploy_date_variable.outputs.suffix }}
